server:
  port: 9003

spring:
  cloud:
    function:
      definition: processShipments;processOrders
    stream:
      bindings:
        #Order totals
        processOrders-in-0:
          destination: order-created-events
          group: order-consumer-group
          content-type: application/*+avro
        processOrders-out-0:
          destination: consumer-orders-total
          content-type: application/*+avro
        processOrders-out-1:
          destination: fraud-alert-orders-total
          content-type: application/*+avro
        #Shipments
        processShipments-in-0:
          destination: consumer-orders-total
          group: shipment-consumer-group
          content-type: application/*+avro
        processShipments-out-0:
          destination: shipment-events
          content-type: application/*+avro
      kafka:
        streams:
          bindings:
            processOrders-in-0.consumer.application-id: order-processor-stream
            processShipments-in-0.consumer.application-id: shipment-processor-stream
          binder:
            application-id: order-processor-stream
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8085
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde