server:
  port: 9002

spring:
  cloud:
    stream:
      function:
        definition: processOrderTotals
      bindings:
        processOrderTotals-in-0:
          destination: consumer-order-totals
          group: processOrderTotals-consumers
          content-type: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            schema.registry.url: http://localhost:8085
            specific.avro.reader: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true
