server:
  port: 9002

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-order-totals-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8085
      topics:
        consumer-order-totals-topic: consumer-order-totals